name = "medusa-backend"
compatibility_date = "2025-12-03"
compatibility_flags = ["nodejs_compat"]

[env.production]
d1_databases = [
  { binding = "DB", database_name = "medusa-db", database_id = "ab56a9dd-6a10-4093-ac2a-84fd4f671012" }
]

[[d1_databases]]
binding = "DB"
database_name = "medusa-db"
database_id = "ab56a9dd-6a10-4093-ac2a-84fd4f671012"

[build]
command = "yarn build"

[build.upload]
format = "modules"
dir = ".medusa/server"
main = "index.js"
